config/routes.rb
Wikipages::Application.routes.draw do
  root :to => 'contacts#index'
  resources :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:notice] = "Contact created."
      redirect_to contacts_path
    else
      render 'new'
    end
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      flash[:notice] = "Contact updated."
      redirect_to contact_path(@contact)
    else
      render 'edit'
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    flash[:notice] = "Contact deleted."
    redirect_to contacts_path
  end

private

  def contact_params
    params.require(:contact).permit(:name, :email, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/edit.html.erb
<h1>Edit contact</h1>

<%= render 'form' %>

app/views/contacts/index.html.erb
<h1>Wikipages</h1>

<%= link_to "New Contact", new_contact_path %>

<ul>
  <% @contacts.each do |contact| %>
    <li><a href="/contacts/<%= contact.id %>"><%= contact.name %></a></li>
  <% end %>
</ul>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

app/views/contacts/show.html.erb
<h1><%= @contact.name %></h1>

<p>Phone: <%= @contact.phone %></p>
<p>Email: <%= @contact.email %></p>

<p><%= link_to "Edit", edit_contact_path(@contact) %></p>
<p><%= link_to "Delete", contact_path(@contact),
                         :confirm => "You sure",
                         :method => "delete" %></p>
<p><%= link_to "Homepage", contacts_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikipages</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <div class="container">
    <%= flash[:notice] %>
    <%= flash[:alert] %>
    <%= yield %>
  </div>



</body>
</html>